[package]
name = "scout_api"
version = "0.1.0"
authors = ["Christopher Ogden <ogdenchris@gmail.com>"]
edition = "2019"

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.9.0"